#!/bin/bash
alias ls="ls -F --color"
alias l="ls --color"
alias ll="ls -la"
alias la="ls -a"
alias t="tar"
alias tv="tar xzvf"
alias tb="tar xjvf"
alias dw="cd ~/Downloads/"
alias chrome="google-chrome 2>/dev/null"
alias emacs="emacs23 -nw"
alias pdf="evince"
alias c="fasd_cd -d"
alias vba="gvba"
alias rand='xrandr --output CRT1 --primary --output LVDS --off'
alias gr="go run"
alias gc="go build"
alias settings='gnome-control-center'
alias v='f -e vim'
alias sl="sl -Fa"
alias SLEEP=sleep
alias tm="tmux"
alias sb="ssh devrs041.prn2.facebook.com"
alias sbp="ssh dev1791.prn2.facebook.com"
alias redshift="redshift -l 37.4225:-122.1423"
alias ec2="ssh sharad@ec2-54-227-30-148.compute-1.amazonaws.com"
