#!/bin/bash
args=`getopt abc:d $*`
set -- $args
for i
do
    if [[ $i == "status" ]];
    then

        message="`nuvolaplayer-client status | grep Song: | sed -e 's/Song: //g'` - `nuvolaplayer-client status | grep Artist: | sed -e 's/Artist: //g'`"
        if [[ $message = '(null) - '  || "$(echo $message | tr -d ' ')" = '-' ]]; then
            echo "No song playing"
        else
            echo $message
        fi
    fi
    if [[ $i == "pause" ]];
    then
        echo "Pausing"
        nuvolaplayer-client $i
    fi
    if [[ $i == "play" ]];
    then
        echo "Playing"
        nuvolaplayer-client $i
    fi
    if [[ $i == "toggle" ]];
    then
        echo "Toggling"
        nuvolaplayer-client $i
    fi
    if [[ $i == "next" ]];
    then
        echo "Next"
        nuvolaplayer-client $i
    fi
    if [[ $i == "prev" ]];
    then
        echo "Previous"
        nuvolaplayer-client $i
    fi
    if [[ $i == "volup" ]];
    then
        echo "Volume Up"
        amixer --quiet set Master 2+
    fi
    if [[ $i == "voldown" ]];
    then
        echo "Volume Down"
        amixer --quiet set Master 2-
    fi
done
