export EDITOR=vim
export PS1='\[\033[01;32m\]\u@\h\[\033[01;34m\] \w \$\[\033[00m\] '
export PATH=$PATH:$HOME/bin/
export WORKON_HOME=~/.envs
export TERM=xterm-256color
export PATH=$PATH:/home/local/ANT/sharadv/lib/mendeleydesktop/bin/

source ~/.bash_aliases
source ~/.bash_git
source ~/.bash_functions
source ~/.bash_go
