export EDITOR=vim
export PS1='\[\033[01;32m\]\u@\h\[\033[01;34m\] \w \$\[\033[00m\] '
export WORKON_HOME=~/.envs
export TERM=xterm-256color
export PATH=$PATH:/home/sharad/local/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/home/sharad/local/lib
export LIBRARY_PATH=$LIBRARY_PATH:/home/sharad/local/lib

source ~/.bash_aliases
source ~/.bash_git
source ~/.bash_functions
source ~/.bash_go
